Repository UMC-6th-bwither/Front-end, pull requests merged in 2024-08, with the labels that each got.

#58 개발 범위 변경으로 인한 컴포넌트 업데이트
  src/App.jsx
  src/components/BreederContactCard/BreederContactCard.jsx
  src/components/Editor/Editor.jsx
  src/components/Editor/TitleForm/TitleForm.jsx
  src/components/Editor/styles.css
  src/components/PostCard/MyPostCard.jsx
  src/components/PostCard/PostCard.jsx
  src/components/buttonselector/ButtonSelector.jsx
  src/components/buttonselector/ButtonSelector.style.js
  src/pages/Community/BreederInformation/BreederInformation.jsx
  src/pages/Community/menuItems.js
  src/pages/MyReview/Review/Form/Form.jsx
  src/pages/MyReview/Review/Form/Form.style.js
  src/pages/MyReview/Review/Form/Title.style.js
  src/pages/MyReview/Review/Review.jsx
  src/pages/MyReview/Save/Save.jsx
  src/pages/NotFound/NotFound.jsx
  src/pages/NotFound/NotFound.style.js
  src/pages/WritingFormGeneral/WritingFormGeneral.jsx
  src/pages/WritingFormGeneral/menuItems.js
Labels: 🎨 Html&css

#61 브위더 후기 페이지 디자인 수정
  src/components/BreederReview/ReviewModal.jsx
  src/components/BwitherReview/ReviewModal.jsx
  src/pages/BreederReview/BreederReview.style.js
  src/pages/BwitherReview/BwitherReview.jsx
  src/pages/BwitherReview/BwitherReview.style.js
Labels: ✨ feature, 🎨 Html&css

#64 ✨ Feat: 브위더 회원가입 로직 추가
  src/components/SignUpAgreement/Agreement.jsx
  src/components/SignUpTerms/SignUpTerms.jsx
  src/pages/SignUpBwither/BwitherSignUp.style.js
  src/pages/SignUpBwither/BwitherSignUp1.jsx
  src/pages/SignUpBwither/BwitherSignUp2.jsx
  src/pages/SignUpBwither/BwitherSignUp3.jsx
Labels: ✨ feature, 🎨 Html&css

#65 ✨ Feat: 브리더 회원가입 1,3,5 구현
  src/pages/SignUpBreeder/BreederSignUp1.jsx
  src/pages/SignUpBreeder/BreederSignUp3.jsx
  src/pages/SignUpBreeder/BreederSignUp5.jsx
Labels: ✨ feature, 🎨 Html&css

#66 ✨ FEAT: Header에 경로 추가
  src/components/header/Header.jsx
Labels: ✨ feature

#67 ✨ FEAT: 브위더 회원가입 라우팅 추가
  src/App.jsx
Labels: ✨ feature

#68 ✨ FEAT: 브리더 회원가입 라우팅 추가
  src/App.jsx
Labels: ✨ feature

#69 ✨ Feat: 분양시스템 페이지 디자인, 라우팅 추가
  src/App.jsx
  src/pages/AdoptionSystem/AdoptionSystem.jsx
  src/pages/AdoptionSystem/AdoptionSystem.style.js
Labels: ✨ feature, 🎨 Html&css

#73 🐛 Fix: 브리더 세부정보 페이지 기능 수정
  src/components/BreederDetail/BreederReview.jsx
  src/pages/BreederInfoEdit/BreederInfoEdit.jsx
  src/pages/BreederInfoEdit/BreederInfoEdit.style.js
Labels: ✨ feature

#72 🎨 헤더 라우팅 설정, 브리더 회원가입 폼 작성
  src/App.jsx
  src/components/DropBoxes/DropBox.style.js
  src/components/header/Header.jsx
  src/components/header/Header.style.js
  src/pages/AdoptionSystem/AdoptionSystem.style.js
  src/pages/Community/menuItems.js
  src/pages/CommunityMain/CommunityMain.jsx
  src/pages/SignUpBwither/BwitherSignUp1.jsx
  src/pages/SignUpBwither/BwitherSignUp2.jsx
  src/pages/SignUpBwither/BwitherSignUp3.jsx
  src/pages/SignupBreeder/BreederSignUp.style.js
  src/pages/SignupBreeder/BreederSignUp4.jsx
Labels: ✨ feature, 🎨 Html&css

#74 🐛 URL 재설정, 헤더 링크 재설정, import 오류 해결
  package-lock.json
  public/icons/fence.svg
  src/App.jsx
  src/components/BreederCard/BreederCard.jsx
  src/components/BreederCard/BreederCard.style.js
  src/components/header/Header.jsx
  src/pages/AdoptionSystem/AdoptionSystem.jsx
  src/pages/BwitherReview/BwitherReview.jsx
  src/pages/BwitherReview/BwitherReview.style.js
  src/pages/SignUpBreeder/BreederSignUp1.jsx
  src/pages/SignUpBreeder/BreederSignUp3.jsx
  src/pages/SignUpBreeder/SignUpBreederChoice.jsx
  src/pages/SignUpBreeder/SignUpBreederInfo.jsx
  src/pages/SignupBreeder/BreederSignUp4.jsx
Labels: 🐛 fix, 🎨 Html&css

#76 프로필 수정 페이지 드랍다운 컴포넌트 추가
  src/components/ProfileSettingDropBox/ProfileSettingDropBox.jsx
  src/components/ProfileSettingDropBox/ProfileSettingDropBox.style.js
  src/pages/ProfileSetting/ProfileSetting.style.js
  src/pages/ProfileSetting/ProfileSettingBreeder.jsx
Labels: ✨ feature, 🎨 Html&css

#75 ♻️ 컴포넌트 클릭 시 link 작업 & 일부 페이지 디자인 조정
  src/components/BreederCard/BreederCard.jsx
  src/components/BreederCard/BreederCard.style.js
  src/components/BreederContactCard/BreederContactCard.jsx
  src/components/DogCard/DogCard.jsx
  src/components/DogCard/DogCard.style.js
  src/pages/AnimalList/AnimalList.jsx
  src/pages/BreederList/BreederList.jsx
  src/pages/Community/BreederInformation/BreederInformation.jsx
  src/pages/Community/Community.style.js
  src/pages/MyReview/Animal/Animal.jsx
  src/pages/MyReview/Animal/Animal.style.js
  src/pages/MyReview/Breeder/Breeder.jsx
  src/pages/MyReview/Breeder/Breeder.style.js
  src/pages/MyReview/Review/Form/Form.jsx
  src/pages/MyReview/Review/Review.jsx
  src/pages/MyReview/Save/Save.jsx
Labels: ♻️ refactor

#78 ✨ Feat: 브위더 회원가입 추가 구현
  public/icons/signUp/check_after.svg
  public/icons/signUp/check_before.svg
  src/components/SignUpAgreement/Agreement.jsx
  src/components/SignUpAgreement/Agreement.style.js
  src/components/SignUpTerms/SignUpTerms.jsx
  src/components/SignUpTerms/SignUpTerms.style.js
  src/pages/SignUpBwither/BwitherSignUp.style.js
  src/pages/SignUpBwither/BwitherSignUp1.jsx
  src/pages/SignUpBwither/BwitherSignUp2.jsx
  src/pages/SignUpBwither/BwitherSignUp3.jsx
Labels: ✨ feature, 🎨 Html&css

#79 ✨ Feat: 브리더 회원가입 추가 구현
  src/App.jsx
  src/pages/SignUpBreeder/BreederSignUp1.jsx
  src/pages/SignUpBreeder/BreederSignUp2.jsx
  src/pages/SignUpBreeder/BreederSignUp3.jsx
  src/pages/SignUpBreeder/BreederSignUp5.jsx
  src/pages/SignUpBreeder/SignUpBreeder.style.js
  src/pages/SignupBreeder/BreederSignUp.style.js
  src/pages/SignupBreeder/BreederSignUp4.jsx
Labels: ✨ feature, 🎨 Html&css

#80 ✨ Feat: 로그인 페이지 구현
  src/pages/Login/Login.jsx
  src/pages/Login/Login.style.js
  src/pages/SignUpBwither/BwitherSignUp4.jsx
Labels: ✨ feature, 🎨 Html&css

#81 ✨ Feat: Header에 경로 추가
  src/components/header/Header.jsx
  src/components/header/Header.style.js
Labels: ✨ feature

#82 🐛 Fix: 브위더 회원가입 autoFocus 오류 해결
  src/pages/SignUpBwither/BwitherSignUp1.jsx
  src/pages/SignUpBwither/BwitherSignUp2.jsx
Labels: 🐛 fix

#83 ✨ Feat: 브리더 회원가입 aufoFocus 오류 해결 및 브리더 회원가입2 태그 초기화 로직 추가
  src/pages/SignUpBreeder/BreederSignUp1.jsx
  src/pages/SignUpBreeder/BreederSignUp2.jsx
  src/pages/SignUpBreeder/BreederSignUp3.jsx
Labels: ✨ feature, 🐛 fix

#88 ✨ Feat: api 로직 모듈화
  src/apis/api.js
Labels: ✨ feature

#89 ✨ Feat: 로그인 api 연결
  src/apis/postUser.js
  src/pages/Login/Login.jsx
  src/pages/Login/Login.style.js
Labels: ✨ feature

#91 ✨ 로그인 hook useAuth 생성
  src/hooks/useAuth.js
  src/pages/Community/BreederInformation/BreederInformation.jsx
  src/pages/Login/Login.jsx
  src/utils/extractContextFromBlocks.js
  src/utils/extractImgSrcFromBlocks.js
  src/utils/handleLogin.js
Labels: ✨ feature

#93 🐛 Hook(useAuth) 새로고침 시 로그인 상태 유지 버그 fix
  src/App.jsx
  src/components/BreederContactCard/BreederContactCard.jsx
  src/pages/Community/BreederInformation/BreederInformation.jsx
  src/pages/MyReview/Review/Form/Form.jsx
  src/pages/MyReview/Review/Review.jsx
  src/pages/MyReview/Save/Save.jsx
  src/pages/WritingFormGeneral/WritingFormGeneral.jsx
Labels: 🐛 fix

#94 ✨ Feat: 로그인 상태에 따라 Header 바뀌는 로직 추가
  src/components/header/Header.jsx
  src/components/header/Header.style.js
Labels: ✨ feature

#95 🐛 Fix: Header에서 eslint 에러 수정
  src/components/header/Header.jsx
Labels: 🐛 fix

#96 🚀 배포 준비
  .dockerignore
  .github/workflows/deploy.yml
  Dockerfile
  docker-compose.yml
  index.html
  nginx.conf
  src/components/ChatBreederInfo/ChatBreederInfo.jsx
  src/components/DeleteReasonModal/DeleteReasonModal.jsx
  src/components/DropBoxes/DropBox.jsx
  src/components/Editor/Editor.jsx
  src/components/RecentDogCard/RecentDogCard.jsx
  src/components/ReportModal/ReportModal.jsx
  src/components/SignUpAgreement/Agreement.jsx
  src/components/SignUpTerms/SignUpTerms.jsx
  src/components/header/Header.jsx
  src/pages/AdoptionSystem/AdoptionSystem.jsx
  src/pages/Community/BreederInformation/BreederInformation.jsx
  src/pages/CommunityMain/CommunityMain.jsx
  src/pages/Login/Login.jsx
  src/pages/Main/Main.jsx
  src/pages/MyReview/Animal/Animal.jsx
  src/pages/MyReview/Breeder/Breeder.jsx
  src/pages/MyReview/Review/Form/Form.jsx
  src/pages/MypageBreeder/MypageBreeder.jsx
  src/pages/MypageGeneral/MypageGeneral.jsx
  src/pages/ProfileSetting/ProfileSetting.style.js
  src/pages/SignUpBreeder/BreederSignUp1.jsx
  src/pages/SignUpBreeder/BreederSignUp2.jsx
  src/pages/SignUpBreeder/BreederSignUp3.jsx
  src/pages/SignUpBreeder/BreederSignUp5.jsx
  src/pages/SignUpBreeder/SignUpBreeder.jsx
  src/pages/SignUpBreeder/SignUpBreederChoice.jsx
  src/pages/SignUpBreeder/SignUpBreederDone.jsx
  src/pages/SignUpBreeder/SignUpBreederInfo.jsx
  src/pages/SignUpBreeder/SignUpBreederInfo2.jsx
  src/pages/SignUpBwither/BwitherSignUp1.jsx
  src/pages/SignUpBwither/BwitherSignUp2.jsx
  src/pages/SignUpBwither/BwitherSignUp3.jsx
  src/pages/SignUpBwither/BwitherSignUp4.jsx
  src/pages/SignupBreeder/BreederSignUp4.jsx
  src/pages/WritingDetail/WritingDetail.jsx
  src/pages/WritingFormGeneral/WritingFormGeneral.jsx
  src/utils/convertBlobUrlToHttpUrl.js
  src/utils/extractImgSrcFromBlocks.js
  update_and_deploy.sh
  vite.config.js
Labels: ✨ feature

#103 ✨ Feat: 브위더/브리더 버전 메인페이지, 커뮤니티 글 상세페이지, 브위더/브리더 프로필 변경 페이지 api 연결
  public/img/bannerimg2.png
  public/img/bannerimg3.png
  public/img/bannerimg4.png
  src/App.jsx
  src/components/ProfileSettingDropBox/ProfileSettingDropBox.style.js
  src/pages/Main/Main.jsx
  src/pages/Main/Main.style.js
  src/pages/ProfileSetting/ProfileSetting.style.js
  src/pages/ProfileSetting/ProfileSettingBreeder.jsx
  src/pages/ProfileSetting/ProfileSettingGeneral.jsx
  src/pages/WritingDetail/WritingDetail.jsx
Labels: ✨ feature

#105 ✨ Feat: 로그인 로직 추가
  src/pages/Login/Login.jsx
  src/pages/Login/Login.style.js
Labels: ✨ feature, 🎨 Html&css

#106 ✨ Feat: 브위더 회원가입 api 연결
  public/icons/signUp/complete_check.svg
  src/apis/postUser.js
  src/components/SignUpDropdown/Dropdown.jsx
  src/components/SignUpDropdown/Dropdown.style.js
  src/components/SignUpTerms/SignUpTerms.jsx
  src/components/SignUpTerms/SignUpTerms.style.js
  src/pages/SignUpBwither/BwitherSignUp.style.js
  src/pages/SignUpBwither/BwitherSignUp1.jsx
  src/pages/SignUpBwither/BwitherSignUp2.jsx
  src/redux/signupSlice.jsx
  src/redux/store.jsx
Labels: ✨ feature, 🎨 Html&css

#107 ✨ Feat: 브리더 회원가입 api 연결
  src/apis/api.js
  src/apis/postUser.js
  src/pages/SignUpBreeder/BreederSignUp1.jsx
  src/pages/SignUpBreeder/BreederSignUp2.jsx
  src/pages/SignUpBreeder/BreederSignUp3.jsx
  src/pages/SignUpBreeder/SignUpBreeder.style.js
  src/pages/SignupBreeder/BreederSignUp.style.js
  src/pages/SignupBreeder/BreederSignUp4.jsx
  src/redux/breederSignupSlice.jsx
  src/redux/store.jsx
Labels: ✨ feature, 🎨 Html&css

#108 🐛 Fix: import 에러 해결
  src/components/SignUpTerms/SignUpTerms.jsx
Labels: 🐛 fix

#109 🐛 Fix: 브리더 회원가입 import 에러 해결
  src/pages/SignUpBreeder/BreederSignUp1.jsx
  src/pages/SignUpBreeder/BreederSignUp2.jsx
  src/pages/SignUpBreeder/BreederSignUp3.jsx
Labels: 🐛 fix

#110 ✨ Feat: 브리더 회원가입 약관 체크박스 연동 및 이메일 인증 api 연결
  src/pages/SignUpBreeder/BreederSignUp1.jsx
Labels: ✨ feature, 🎨 Html&css

#111 🐛 Fix: BreederSignUp4 폴더명 대소문자 구분 못해서 난 에러 수정
  src/pages/SignUpBreeder/BreederSignUp.style.js
  src/pages/SignUpBreeder/BreederSignUp4.jsx
Labels: 🐛 fix

#112 ✨ BreederList, AnimalList, BreederAniamlList, Animal, Breeder, MypageGeneral, MypageBreeder api 연결
  public/icons/signUp/datepicker_arrow_next.svg
  public/icons/signUp/datepicker_arrow_previous.svg
  public/img/location.svg
  public/img/nothing_bowl.svg
  src/components/BreederCard/BreederCard.jsx
  src/components/BreederCard/BreederCard.style.js
  src/components/DogCard/DogCard.jsx
  src/components/DogCard/DogCard.style.js
  src/components/RecentBreederCard/RecentBreederCard.jsx
  src/components/RecentBreederCard/RecentBreederCard.style.js
  src/components/RecentDogCard/RecentDogCard.jsx
  src/components/RecentDogCard/RecentDogCard.style.js
  src/components/ReservationDogCard/ReservationDogCard.jsx
  src/components/ReservationDogCard/ReservationDogCard.style.js
  src/pages/AnimalList/AnimalList.jsx
  src/pages/AnimalList/AnimalList.style.js
  src/pages/BreederAnimalList/BreederAnimalList.jsx
  src/pages/BreederAnimalList/BreederAnimalList.style.js
  src/pages/BreederList/BreederList.jsx
  src/pages/BreederList/BreederList.style.js
  src/pages/MyReview/Animal/Animal.jsx
  src/pages/MyReview/Animal/Animal.style.js
  src/pages/MyReview/Breeder/Breeder.jsx
  src/pages/MyReview/Breeder/Breeder.style.js
  src/pages/MypageBreeder/MypageBreeder.jsx
  src/pages/MypageBreeder/MypageBreeder.style.js
  src/pages/MypageGeneral/MypageGeneral.jsx
  src/pages/MypageGeneral/MypageGeneral.style.js
  src/pages/MypageGeneral/waitingData.js
  src/pages/SignUpBreeder/SignUpBreeder.jsx
  src/pages/SignUpBreeder/SignUpBreeder.style.js
  src/pages/SignUpBreeder/SignUpBreederInfo2.jsx
  src/pages/selectData.js
Labels: ✨ feature, ♻️ refactor, 🎨 Html&css

#114 ✨ Feat: 분양시스템 측면 메뉴셀렉터 추가
  src/components/AdoptionSystemMenu/AdoptionSystemMenu.jsx
  src/pages/AdoptionSystem/AdoptionSystem.jsx
  src/pages/AdoptionSystem/AdoptionSystem.style.js
Labels: ✨ feature, 🎨 Html&css

#102 ✨ BreederInfoEdit 페이지 API 연결
  defaultprofile.png
  src/components/BreederInfoEdit/BreederInfo.jsx
  src/components/BreederInfoEdit/BreederQna.jsx
  src/components/BreederInfoEdit/KennelInfo.jsx
  src/components/BreederReviewAnimalCard/BreederReviewAnimalCard.jsx
  src/components/MenuSelect/MenuSelect.jsx
  src/components/MenuSelect/MenuSelect.style.js
  src/components/PostCard/MyPostCard.jsx
  src/components/PostCard/PostCard.jsx
  src/components/PostCard/PostCard.style.js
  src/pages/AdoptionSystem/AdoptionSystem.jsx
  src/pages/BreederInfoEdit/BreederInfoEdit.jsx
  src/pages/BreederInfoEdit/BreederInfoEdit.style.js
  src/pages/BreederInfoEdit/styles.css
  src/pages/Community/BreederInformation/BreederInformation.jsx
  src/pages/MyReview/Review/Review.jsx
  src/pages/MyReview/Save/Save.jsx
  src/pages/SignupBreeder/BreederSignUp4.jsx
  src/utils/convertBlobUrlsToFileList.js
Labels: ✨ feature, ♻️ refactor

#115 BreederSignUp 페이지 오류
  src/pages/AdoptionSystem/AdoptionSystem.jsx
  src/pages/BreederInfoEdit/BreederInfoEdit.jsx
Labels: 🐛 fix

#116 ✨ WritingDetail 디자인 조정 & BreederInfoEdit 페이지 API 연결
  src/pages/BreederInfoEdit/BreederInfoEdit.jsx
  src/pages/SignUpBreeder/SignUpBreeder.style.js
  src/pages/WritingDetail/WritingDetail.style.js
Labels: ✨ feature, ♻️ refactor, 🐛 fix

#119 ✨ Feat: Header role에 따라 바뀌게 구현
  src/components/header/Header.jsx
Labels: ✨ feature, 🎨 Html&css

#120 ✨ Feat: Header에 플로팅박스 추가
  src/components/header/Header.jsx
  src/components/header/Header.style.js
  src/components/header/HeaderModal.jsx
Labels: ✨ feature, 🎨 Html&css

#121 💄 Design: 눈 아이콘 바뀌게 구현
  public/icons/signUp/open_eye.svg
  src/pages/Login/Login.jsx
Labels: 🎨 Html&css

#122 💄 Design: 회원가입 페이지 눈모양 아이콘 바뀌게 구현
  src/pages/SignUpBreeder/BreederSignUp1.jsx
  src/pages/SignUpBwither/BwitherSignUp1.jsx
Labels: 🎨 Html&css

#123 ✨ 브리더 마이페이지 수정 API 연결
  src/components/BreederContactCard/BreederContactCard.jsx
  src/components/BreederInfoEdit/BreederInfo.jsx
  src/components/BreederInfoEdit/BreederQna.jsx
  src/components/BreederInfoEdit/KennelInfo.jsx
  src/components/BreederReviewAnimalCard/BreederReviewAnimalCard.jsx
  src/components/BreederReviewAnimalCard/BreederReviewAnimalCard.style.js
  src/pages/BreederInfoEdit/BreederInfoEdit.jsx
  src/pages/MyReview/MyReview.style.js
  src/pages/MyReview/Review/Form/Form.jsx
  src/pages/MyReview/Review/Review.jsx
  src/pages/MypageBreeder/MypageBreeder.jsx
  src/utils/loadImageFromUrl.js
Labels: ✨ feature, ♻️ refactor

#124 ✨ Feat: 회원가입과 약관동의 상세페이지 연결
  src/components/SignUpTerms/SignUpTerms.jsx
  src/components/SignUpTerms/SignUpTerms.style.js
  src/pages/TermsOfService/TermsOfService.jsx
  src/redux/menuSlice.jsx
  src/redux/store.jsx
  src/redux/termsSlice.jsx
Labels: ✨ feature, 🎨 Html&css

#125 ✨ Feat: 브리더 받은 후기 api 연동 중
  src/apis/getBreederReview.js
  src/hooks/useAuth.js
  src/pages/BreederReview/BreederReview.jsx
  src/redux/authSlice.jsx
  src/utils/handleLogin.js
Labels: ✨ feature

#126 ✨ 우편번호 검색 기능 추가
  package-lock.json
  package.json
  src/components/AddressSearch/AddressSearch.jsx
  src/components/AddressSearch/AddressSearchModal.jsx
  src/pages/SignUpBreeder/BreederSignUp4.jsx
  src/pages/SignUpBwither/BwitherSignUp2.jsx
Labels: ✨ feature, 🎨 Html&css

#127 🐛 Fix: 종 드롭다운 첫번째 옵션 선택 안 되는 오류 수정
  src/pages/SignUpBreeder/BreederSignUp2.jsx
Labels: 🐛 fix

#129 ✨ Feat: yyyy-MM-dd로 선택되게 수정
  src/pages/SignUpBreeder/BreederSignUp4.jsx
Labels: ✨ feature

#128 ✨ 받은 후기 API 연결 작업 & 정보 수정 페이지 오류 해결
  src/components/BreederInfoEdit/BreederInfo.jsx
  src/components/BreederInfoEdit/KennelInfo.jsx
  src/pages/BreederInfoEdit/BreederInfoEdit.jsx
  src/pages/BreederReview/BreederReview.jsx
  src/pages/BreederReview/BreederReview.style.js
  src/pages/Community/BreederInformation/BreederInformation.jsx
  yarn.lock
Labels: ✨ feature, 🐛 fix, 🎨 Html&css

#131 ✨ Feat: 회원가입 유효성 검사 추가
  src/pages/SignUpBreeder/BreederSignUp.style.js
  src/pages/SignUpBreeder/BreederSignUp1.jsx
  src/pages/SignUpBreeder/BreederSignUp2.jsx
  src/pages/SignUpBreeder/BreederSignUp3.jsx
  src/pages/SignUpBreeder/BreederSignUp4.jsx
  src/pages/SignUpBreeder/SignUpBreeder.style.js
  src/pages/SignUpBwither/BwitherSignUp.style.js
  src/pages/SignUpBwither/BwitherSignUp1.jsx
  src/pages/SignUpBwither/BwitherSignUp2.jsx
Labels: ✨ feature, 🎨 Html&css

#132 ✨ Feat: 브위더 리뷰 페이지, 상세페이지 레이아웃 변경, 메인페이지 브위더 세부정보 바로가기 추가
  package-lock.json
  package.json
  public/img/ReviewCardDefault.png
  public/img/rating0.png
  public/img/rating1.png
  public/img/rating2.png
  public/img/rating3.png
  public/img/rating4.png
  public/img/rating5.png
  src/pages/BwitherReview/BwitherReview.jsx
  src/pages/BwitherReview/BwitherReview.style.js
  src/pages/Main/Main.jsx
  src/pages/ProfileSetting/ProfileSettingGeneral.jsx
  src/pages/WritingDetail/WritingDetail.jsx
  src/pages/WritingDetail/WritingDetail.style.js
  yarn.lock
Labels: ✨ feature, ♻️ refactor, 🎨 Html&css

#134 💄 Design: 브리더 상세 신뢰등급 삭제
  src/pages/BreederDetail/BreederDetail.jsx
  src/pages/BreederDetail/BreederDetail.style.js
Labels: 🎨 Html&css

#139 🐛 BreederInfoEdit 저장 오류
  defaultprofile.png
  src/components/PostCard/MyPostCard.jsx
  src/components/PostCard/PostCard.style.js
  src/pages/BreederInfoEdit/BreederInfoEdit.jsx
  src/pages/MyReview/Post/Post.jsx
  src/pages/MyReview/Save/Save.jsx
Labels: 🐛 fix

#146 ✨ Feat: Header와 플로팅박스 수정
  src/components/header/Header.jsx
  src/components/header/HeaderModal.jsx
Labels: ✨ feature, 🎨 Html&css

#147 ✨ Feat: 브리더 랭킹 전체보기 추가, 글상세보기 북마크 수정
  src/pages/Main/Main.jsx
  src/pages/WritingDetail/WritingDetail.jsx
Labels: ♻️ refactor

#152 브위더 리뷰 페이지, 상세페이지 북마크 기능 수정
  src/pages/BwitherReview/BwitherReview.jsx
  src/pages/WritingDetail/WritingDetail.jsx
Labels: ♻️ refactor, 🐛 fix

#157 🐛 XHR 중복 요청 패치
  src/components/header/Header.jsx
  src/pages/Community/Community.style.js
  src/pages/MyReview/MyReview.style.js
  src/pages/MyReview/Save/Save.jsx
Labels: 🐛 fix, 🎨 Html&css

#158 ✨ Feat: 로그인 아이디/비밀번호 불일치 시 유효성 검사 추가
  src/pages/Login/Login.jsx
Labels: ✨ feature, 🎨 Html&css

#159 ✨ 후기 삭제 버튼 추가
  src/components/BreederReviewAnimalCard/BreederReviewAnimalCard.jsx
  src/components/BreederReviewAnimalCard/BreederReviewAnimalCard.style.js
  src/pages/MyReview/Review/Review.jsx
Labels: ✨ feature

#160 🐛 Fix: Header 프로필사진 바뀌게 수정
  src/App.jsx
Labels: ✨ feature, 🎨 Html&css

#161 메인페이지 꿀정보 상호명 수정, 일반유저 프로필 변경페이지 수정
  src/pages/Main/Main.jsx
  src/pages/ProfileSetting/ProfileSettingGeneral.jsx
  src/pages/WritingDetail/WritingDetail.jsx
Labels: ♻️ refactor

#162 🐛 메인페이지 리뷰 미리보기 텍스트 수정
  src/pages/Main/Main.jsx
Labels: ✨ feature

#163 🐛 Fix: 브위더 회원가입 로직 및 디자인 수정
  src/components/SignUpButton/Button.jsx
  src/components/SignUpTerms/SignUpTerms.jsx
  src/pages/SignUpBwither/BwitherSignUp.style.js
  src/pages/SignUpBwither/BwitherSignUp1.jsx
  src/pages/SignUpBwither/BwitherSignUp2.jsx
  src/pages/TermsOfService/TermsOfService.jsx
  src/redux/signupSlice.jsx
Labels: 🐛 fix, 🎨 Html&css
